# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Langenkaemper\Documents\Uni\PhD\Python\Federpruefstand/GUI_Federpruefstand.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1033, 675)
        MainWindow.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("../Masterarbeit Hakan/NiTiFeder.jpg"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setMaximumSize(QtCore.QSize(791, 450))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.graphicsView = PlotWidget(self.tab)
        self.graphicsView.setGeometry(QtCore.QRect(0, 0, 781, 421))
        self.graphicsView.setMinimumSize(QtCore.QSize(781, 421))
        self.graphicsView.setObjectName("graphicsView")
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.graphicsView_2 = PlotWidget(self.tab_2)
        self.graphicsView_2.setGeometry(QtCore.QRect(0, 0, 781, 421))
        self.graphicsView_2.setObjectName("graphicsView_2")
        self.tabWidget.addTab(self.tab_2, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 1, 1, 3)
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setMinimumSize(QtCore.QSize(218, 280))
        self.groupBox_2.setMaximumSize(QtCore.QSize(218, 280))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.formLayoutWidget = QtWidgets.QWidget(self.groupBox_2)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 20, 212, 241))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_actualT = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_actualT.setFont(font)
        self.label_actualT.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_actualT.setAlignment(QtCore.Qt.AlignCenter)
        self.label_actualT.setObjectName("label_actualT")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.label_actualT)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_length = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_length.setFont(font)
        self.label_length.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_length.setAlignment(QtCore.Qt.AlignCenter)
        self.label_length.setObjectName("label_length")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_length)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.label_cycleno = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_cycleno.setFont(font)
        self.label_cycleno.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_cycleno.setAlignment(QtCore.Qt.AlignCenter)
        self.label_cycleno.setObjectName("label_cycleno")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_cycleno)
        self.label_7 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.label_8 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.label_setTmax = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_setTmax.setFont(font)
        self.label_setTmax.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_setTmax.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setTmax.setObjectName("label_setTmax")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.label_setTmax)
        self.label_setTmin = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_setTmin.setFont(font)
        self.label_setTmin.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_setTmin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setTmin.setObjectName("label_setTmin")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.label_setTmin)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.LabelRole, spacerItem)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(6, QtWidgets.QFormLayout.FieldRole, spacerItem1)
        self.label_11 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_11)
        self.label_resistance = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_resistance.setFont(font)
        self.label_resistance.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_resistance.setAlignment(QtCore.Qt.AlignCenter)
        self.label_resistance.setObjectName("label_resistance")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_resistance)
        self.label_13 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.LabelRole, self.label_13)
        self.label_setheatingrate = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_setheatingrate.setFont(font)
        self.label_setheatingrate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_setheatingrate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setheatingrate.setObjectName("label_setheatingrate")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.FieldRole, self.label_setheatingrate)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.LabelRole, spacerItem2)
        spacerItem3 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(11, QtWidgets.QFormLayout.LabelRole, spacerItem3)
        spacerItem4 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(11, QtWidgets.QFormLayout.FieldRole, spacerItem4)
        spacerItem5 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.formLayout.setItem(0, QtWidgets.QFormLayout.FieldRole, spacerItem5)
        self.label_setmeasurerate = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_setmeasurerate.setFont(font)
        self.label_setmeasurerate.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_setmeasurerate.setAlignment(QtCore.Qt.AlignCenter)
        self.label_setmeasurerate.setObjectName("label_setmeasurerate")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.FieldRole, self.label_setmeasurerate)
        self.label_14 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.formLayout.setWidget(10, QtWidgets.QFormLayout.LabelRole, self.label_14)
        self.gridLayout.addWidget(self.groupBox_2, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setMinimumSize(QtCore.QSize(900, 140))
        self.groupBox.setMaximumSize(QtCore.QSize(900, 140))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.groupBox)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(10, 20, 881, 112))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.formLayout_2 = QtWidgets.QFormLayout()
        self.formLayout_2.setObjectName("formLayout_2")
        self.t_maxLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.t_maxLabel.setFont(font)
        self.t_maxLabel.setObjectName("t_maxLabel")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.t_maxLabel)
        self.t_maxLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_maxLineEdit.sizePolicy().hasHeightForWidth())
        self.t_maxLineEdit.setSizePolicy(sizePolicy)
        self.t_maxLineEdit.setObjectName("t_maxLineEdit")
        self.formLayout_2.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.t_maxLineEdit)
        self.t__minLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.t__minLabel.setFont(font)
        self.t__minLabel.setObjectName("t__minLabel")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.t__minLabel)
        self.t__minLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t__minLineEdit.sizePolicy().hasHeightForWidth())
        self.t__minLineEdit.setSizePolicy(sizePolicy)
        self.t__minLineEdit.setInputMask("")
        self.t__minLineEdit.setObjectName("t__minLineEdit")
        self.formLayout_2.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.t__minLineEdit)
        self.heatingRateLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.heatingRateLabel.setFont(font)
        self.heatingRateLabel.setObjectName("heatingRateLabel")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.heatingRateLabel)
        self.heatingRateLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.heatingRateLineEdit.sizePolicy().hasHeightForWidth())
        self.heatingRateLineEdit.setSizePolicy(sizePolicy)
        self.heatingRateLineEdit.setObjectName("heatingRateLineEdit")
        self.formLayout_2.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.heatingRateLineEdit)
        self.pushButton_3 = QtWidgets.QPushButton(self.horizontalLayoutWidget)
        self.pushButton_3.setObjectName("pushButton_3")
        self.formLayout_2.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pushButton_3)
        self.horizontalLayout.addLayout(self.formLayout_2)
        self.formLayout_3 = QtWidgets.QFormLayout()
        self.formLayout_3.setObjectName("formLayout_3")
        self.measureRateLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.measureRateLabel.setFont(font)
        self.measureRateLabel.setObjectName("measureRateLabel")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.measureRateLabel)
        self.measureRateLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.measureRateLineEdit.sizePolicy().hasHeightForWidth())
        self.measureRateLineEdit.setSizePolicy(sizePolicy)
        self.measureRateLineEdit.setObjectName("measureRateLineEdit")
        self.formLayout_3.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.measureRateLineEdit)
        self.maximalCyclesLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.maximalCyclesLabel.setFont(font)
        self.maximalCyclesLabel.setObjectName("maximalCyclesLabel")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.maximalCyclesLabel)
        self.saveFolderPathLabel = QtWidgets.QLabel(self.horizontalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.saveFolderPathLabel.setFont(font)
        self.saveFolderPathLabel.setObjectName("saveFolderPathLabel")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.saveFolderPathLabel)
        self.saveFolderPathLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.saveFolderPathLineEdit.sizePolicy().hasHeightForWidth())
        self.saveFolderPathLineEdit.setSizePolicy(sizePolicy)
        self.saveFolderPathLineEdit.setObjectName("saveFolderPathLineEdit")
        self.formLayout_3.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.saveFolderPathLineEdit)
        self.maximalCyclesLineEdit = QtWidgets.QLineEdit(self.horizontalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.maximalCyclesLineEdit.sizePolicy().hasHeightForWidth())
        self.maximalCyclesLineEdit.setSizePolicy(sizePolicy)
        self.maximalCyclesLineEdit.setObjectName("maximalCyclesLineEdit")
        self.formLayout_3.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.maximalCyclesLineEdit)
        self.horizontalLayout.addLayout(self.formLayout_3)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 2)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSizeConstraint(QtWidgets.QLayout.SetMinAndMaxSize)
        self.verticalLayout_2.setSpacing(8)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_2.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setObjectName("pushButton_2")
        self.verticalLayout_2.addWidget(self.pushButton_2)
        self.gridLayout.addLayout(self.verticalLayout_2, 1, 2, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1033, 21))
        self.menubar.setObjectName("menubar")
        self.menuData = QtWidgets.QMenu(self.menubar)
        self.menuData.setObjectName("menuData")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionExit = QtWidgets.QAction(MainWindow)
        self.actionExit.setObjectName("actionExit")
        self.menuData.addAction(self.actionExit)
        self.menubar.addAction(self.menuData.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.t_maxLineEdit, self.t__minLineEdit)
        MainWindow.setTabOrder(self.t__minLineEdit, self.heatingRateLineEdit)
        MainWindow.setTabOrder(self.heatingRateLineEdit, self.measureRateLineEdit)
        MainWindow.setTabOrder(self.measureRateLineEdit, self.maximalCyclesLineEdit)
        MainWindow.setTabOrder(self.maximalCyclesLineEdit, self.saveFolderPathLineEdit)
        MainWindow.setTabOrder(self.saveFolderPathLineEdit, self.pushButton_3)
        MainWindow.setTabOrder(self.pushButton_3, self.pushButton)
        MainWindow.setTabOrder(self.pushButton, self.pushButton_2)
        MainWindow.setTabOrder(self.pushButton_2, self.tabWidget)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Spring Testing"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Experiment Overview"))
        self.label.setText(_translate("MainWindow", "Actual Temperature  / °C:"))
        self.label_actualT.setText(_translate("MainWindow", "TextLabel"))
        self.label_3.setText(_translate("MainWindow", "Length / mm:"))
        self.label_length.setText(_translate("MainWindow", "TextLabel"))
        self.label_4.setText(_translate("MainWindow", "Cycle Number:"))
        self.label_cycleno.setText(_translate("MainWindow", "TextLabel"))
        self.label_7.setText(_translate("MainWindow", "Set T_max  / °C:"))
        self.label_8.setText(_translate("MainWindow", "Set T_min  / °C:"))
        self.label_setTmax.setText(_translate("MainWindow", "TextLabel"))
        self.label_setTmin.setText(_translate("MainWindow", "TextLabel"))
        self.label_11.setText(_translate("MainWindow", "Resistance / Ohm:"))
        self.label_resistance.setText(_translate("MainWindow", "TextLabel"))
        self.label_13.setText(_translate("MainWindow", "heating rate  / °Cs^-1:"))
        self.label_setheatingrate.setText(_translate("MainWindow", "TextLabel"))
        self.label_setmeasurerate.setText(_translate("MainWindow", "TextLabel"))
        self.label_14.setText(_translate("MainWindow", "measure rate  / °Cs^-1:"))
        self.groupBox.setTitle(_translate("MainWindow", "Experiment Settings"))
        self.t_maxLabel.setText(_translate("MainWindow", "T_max / °C"))
        self.t__minLabel.setText(_translate("MainWindow", "T_min  / °C"))
        self.heatingRateLabel.setText(_translate("MainWindow", "heating rate  / °Cs^-1"))
        self.pushButton_3.setText(_translate("MainWindow", "Save Settings"))
        self.measureRateLabel.setText(_translate("MainWindow", "Measure rate"))
        self.maximalCyclesLabel.setText(_translate("MainWindow", "Maximal cycles"))
        self.saveFolderPathLabel.setText(_translate("MainWindow", "Save in Path"))
        self.pushButton.setText(_translate("MainWindow", "Start Experiment"))
        self.pushButton_2.setText(_translate("MainWindow", "Stop Experiment"))
        self.menuData.setTitle(_translate("MainWindow", "Data"))
        self.actionExit.setText(_translate("MainWindow", "Exit"))

    def closeEvent(self, event):
        reply = QtGui.QMessageBox.question(self, "Exit Program",
                                           "Are you sure you want to quit?",
                                           QtGui.QMessageBox.Yes,
                                           QtGui.QMessageBox.No)
        if reply == QtGui.QMessageBox.Yes:
            event.accept()
        else:
            event.ignore()

from pyqtgraph import PlotWidget

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())